[build]
builder = "nixpacks"

[deploy]
startCommand = "python gui/web/rt11extract_simple.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
