name: Build RT11 Extractor - Linux Only

on:
  push:
    branches: [ feature/linux-builds ]

jobs:
  build-linux:
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            runner: ubuntu-latest
          - os: ubuntu-latest
            arch: arm64
            runner: ubuntu-24.04-arm64

    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v4

    - name: Debug runner info
      run: |
        echo "Runner info for ${{ matrix.arch }}:"
        echo "OS: $(uname -a)"
        echo "Architecture: $(uname -m)"
        echo "CPU info:"
        cat /proc/cpuinfo | grep -E "model name|Architecture" | head -5
        echo "Expected architecture: ${{ matrix.arch }}"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'


    - name: Install dependencies
      timeout-minutes: 10
      run: |
        echo "Installing Python dependencies..."
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "Dependencies installed successfully"
    
    - name: Verify project structure (Linux)
      run: |
        echo "Verifying project structure for Linux ${{ matrix.arch }}..."
        if [ ! -d "backend/extractors" ]; then
          echo "ERROR: Backend extractors directory not found"
          exit 1
        fi
        if [ ! -f "gui/desktop/rt11extract_gui.py" ]; then
          echo "ERROR: GUI script not found"
          exit 1
        fi
        echo "Project structure verified"

    - name: Install Linux dependencies
      timeout-minutes: 10
      run: |
        echo "Updating package lists..."
        sudo apt-get update
        echo "Installing Linux dependencies..."
        sudo apt-get install -y build-essential libgl1 libglib2.0-0 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
        echo "Linux dependencies installed successfully"

    - name: Build Linux Executables
      timeout-minutes: 15
      run: |
        ARCH_SUFFIX=""
        if [ "${{ matrix.arch }}" = "arm64" ]; then
          ARCH_SUFFIX="-arm64"
        fi
        
        echo "Starting build for Linux ${{ matrix.arch }}..."
        mkdir -p cli
        
        # Using native ARM64 runner - no cross-compilation needed
        
        # Build CLI tools (similar to macOS approach)
        echo "Building rt11extract..."
        pyinstaller --onefile --name rt11extract --paths backend --paths . backend/extractors/rt11extract
        echo "Building rt11extract_universal..."
        pyinstaller --onefile --name rt11extract_universal --paths backend --paths . backend/extractors/rt11extract_universal
        echo "Building universal_extractor..."
        pyinstaller --onefile --name universal_extractor --paths backend --paths . backend/extractors/universal_extractor.py
        echo "Building imd2raw..."
        pyinstaller --onefile --name imd2raw --paths backend --paths . backend/image_converters/imd2raw.py
        
        # Move CLIs to cli folder (like macOS)
        cp dist/rt11extract cli/
        cp dist/rt11extract_universal cli/
        cp dist/universal_extractor cli/
        cp dist/imd2raw cli/
        
        # Make CLIs executable
        chmod +x cli/*
        
        # Build GUI with CLI tools included (exactly like macOS)
        echo "Building GUI executable..."
        pyinstaller --onefile --name RT11ExtractGUI --paths backend --paths . \
          --add-data "backend/extractors:backend/extractors" \
          --add-data "backend/filesystems:backend/filesystems" \
          --add-data "cli:cli" \
          gui/desktop/rt11extract_gui.py
        
        echo "Creating package directory structure..."
        # Create directory structure like macOS but for Linux
        mkdir -p "RT11Extract-Linux${ARCH_SUFFIX}"
        
        # Copy the main GUI executable
        echo "Copying GUI executable..."
        cp dist/RT11ExtractGUI "RT11Extract-Linux${ARCH_SUFFIX}/"
        chmod +x "RT11Extract-Linux${ARCH_SUFFIX}/RT11ExtractGUI"
        
        # Copy CLI tools to the same directory (like macOS approach)
        echo "Copying CLI tools..."
        cp cli/* "RT11Extract-Linux${ARCH_SUFFIX}/"
        
        # Create README for Linux
        cat > "RT11Extract-Linux${ARCH_SUFFIX}/README.txt" << 'EOF'
        RT11 Extract Linux${{ matrix.arch == 'arm64' && ' ARM64' || '' }} Distribution
        
        This package contains the RT11 Extractor with GUI and CLI tools.
        The GUI automatically detects and uses the CLI tools in the same directory.
        
        Included tools:
        - RT11ExtractGUI: Graphical interface (main application)
        - rt11extract: RT-11 filesystem extractor
        - rt11extract_universal: Universal filesystem extractor (recommended)
        - universal_extractor: Universal image extractor
        - imd2raw: ImageDisk (IMD) to RAW converter
        
        Usage:
        GUI Mode: ./RT11ExtractGUI
        CLI Mode: ./rt11extract_universal <disk_image>
        
        The GUI will automatically find and use the CLI tools from the same directory.
        All tools support --help for detailed usage information.
        
        Supported formats: .dsk, .img, .imd disk images
        Supported filesystems: RT-11, Unix PDP-11, RSX-11M+ (ODS-1)
        EOF
        
        # Create tar.gz package
        echo "Creating final package..."
        tar -czf "RT11Extract-Linux${ARCH_SUFFIX}.tar.gz" "RT11Extract-Linux${ARCH_SUFFIX}"
        echo "Package created: RT11Extract-Linux${ARCH_SUFFIX}.tar.gz"
        ls -la "RT11Extract-Linux${ARCH_SUFFIX}.tar.gz"

    - name: Upload Linux x64 Artifact
      if: matrix.arch == 'x64'
      uses: actions/upload-artifact@v4
      with:
        name: RT11Extract-Linux
        path: RT11Extract-Linux.tar.gz

    - name: Upload Linux ARM64 Artifact
      if: matrix.arch == 'arm64'
      uses: actions/upload-artifact@v4
      with:
        name: RT11Extract-Linux-arm64
        path: RT11Extract-Linux-arm64.tar.gz
